server:
  port: 9999
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sfile_hub?useSSL=false&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update # update database when entity change
#      ddl-auto: create # create database when entity change
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect
    show-sql: true
    open-in-view: false # mean: disable lazy load
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0
    timeout: 10000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0
logging:
  level:
    org:
      springframework:
        security: DEBUG
file:
  path: E:\sfilehub
  chunk-size: 20971520 # 20MB